service: haku

provider:
  name: aws
  runtime: python3.7
  websocketApiName: haku-websocket-api
  websocketApiRouteSelectionExpression: $request.body.action
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:us-east-1:236553647570:table/haku-main"
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  websocketConnectionManager:
    handler: handler.websocket_connection_manager
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect

  addLine:
    handler: handler.add_line
    events:
      - websocket:
          route: addLine

  getBoardId:
    handler: handler.get_board_id
    events:
      - websocket:
          route: getBoardId

  init:
    handler: handler.init
    events:
      - websocket:
          route: init

  compressBoard:
    handler: handler.compress_board
    events:
      - schedule: rate(5 minutes)

  # localTest:
  #   handler: handler.local_test

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy: []